// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using deTestFirstCsharp.Models;

namespace deTestFirstCsharp.Models
{
    public partial class GSSWEBContext : DbContext
    {
        public GSSWEBContext()
        {
        }

        public GSSWEBContext(DbContextOptions<GSSWEBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<deTestWebFormMember> deTestWebFormMember { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<deTestWebFormMember>(entity =>
            {
                entity.Property(e => e.id).ValueGeneratedNever();

                entity.Property(e => e.address).HasMaxLength(200);

                entity.Property(e => e.name)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.phone)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.sex).HasMaxLength(10);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

        public DbSet<deTestFirstCsharp.Models.CMemberViewModel>? CMemberViewModel { get; set; }
    }
}