// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace deTestFirstCsharp.Models
{
    public partial class CMemberViewModel
    {
        deTestWebFormMember _deTestWebFormMember { get; set; }
        public CMemberViewModel() {

            _deTestWebFormMember = new deTestWebFormMember();
        }

        public deTestWebFormMember deTestWebFormMemberBody { 
            get { return _deTestWebFormMember; } 
            set { _deTestWebFormMember = value; } 
        }

        [DisplayName("員編")]
        public int id { get { return _deTestWebFormMember.id; } set { _deTestWebFormMember.id = value; } } 
        [DisplayName("姓名")]
        public string name { get { return _deTestWebFormMember.name; } set { _deTestWebFormMember.name = value; } }
        [DisplayName("性別")]
        public string sex { get { return _deTestWebFormMember.sex; } set { _deTestWebFormMember.sex = value; } }
        [DisplayName("電話")]
        public string phone { get { return _deTestWebFormMember.phone; } set { _deTestWebFormMember.phone = value; } }
        [DisplayName("住址")]
        public string address { get { return _deTestWebFormMember.address; } set { _deTestWebFormMember.address = value; } }
    }
}